### ISSUE TITLE
Recipe Compile Error on deploying gunicorn

### ISSUE THREAD

**Issue by noradaiko** [poise/application_python#60]
My recipe:

```
application app_path do
  path app_path
  owner "www-data"
  group "www-data"
  package "git"

  git app_path do
    repository "~~~~"
    user "www-data"
    group "www-data"
  end
  pip_requirements

  gunicorn do
    port 9001
    app_module "manage:app"
  end

  environment ({'HOME' => '/var/www'})
end
```

Error message:

```
================================================================================
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/classifier-api/recipes/api.rb
================================================================================

Errno::ENOENT
-------------
No such file or directory @ dir_initialize - /usr/share/classifier-api

Cookbook Trace:
---------------

  /tmp/kitchen/cache/cookbooks/application_python/files/halite_gem/poise_application_python/resources/gunicorn.rb:59:in `entries'
  /tmp/kitchen/cache/cookbooks/application_python/files/halite_gem/poise_application_python/resources/gunicorn.rb:59:in `default_app_module'

  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/lazy_default.rb:50:in `instance_eval'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/lazy_default.rb:50:in `set_or_return'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/lwrp_polyfill.rb:114:in `block in attribute'
  /tmp/kitchen/cache/cookbooks/classifier-api/recipes/api.rb:70:in `block (2 levels) in from_file'
  /tmp/kitchen/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:149:in `instance_exec'
  /tmp/kitchen/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:149:in `block (3 levels) in _rewire_dsl!'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:125:in `instance_exec'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:125:in `block (2 levels) in declare_resource'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:115:in `block in declare_resource'
  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'

  /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:96:in `declare_resource'
  /tmp/kitchen/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:144:in `public_send'
  /tmp/kitchen/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:144:in `block (2 levels) in _rewire_dsl!'
  /tmp/kitchen/cache/cookbooks/classifier-api/recipes/api.rb:68:in `block in from_file'
  /tmp/kitchen/cache/cookbooks/classifier-api/recipes/api.rb:55:in `from_file'


----------------------
/tmp/kitchen/cache/cookbooks/application_python/files/halite_gem/poise_application_python/resources/gunicorn.rb:

 52:          # checks the app state and then looks for commonly used filenames.
 53:          # Raises an exception if no default can be found.

 55:          # @return [String]
 56:          def default_app_module
 57:            # If set in app_state, use that.
 58:            return app_state[:python_wsgi_module] if app_state[:python_wsgi_module]
 59>>           files = Dir.entries(path)
 60:            # Try to find a known filename.
 61:            candidate_file = %w{wsgi.py main.py app.py application.py}.find {|file| files.include?(file) }
 62:            # Try the first Python file. Do I really want this?
 63:            candidate_file ||= files.find {|file| file.end_with?('.py') }
 64:            if candidate_file
 65:              ::File.basename(candidate_file, '.py')
 66:            else
 67:              raise PoiseApplicationPython::Error.new("Unable to determine app module for #{self}")
 68:            end
```

It occurs because the deploy target directory is not created yet on the compilation time.
It even happens even if specified `app_module` attribute.
How can I avoid it? How to specify `python_wsgi_module` of `app_state`?

**Comment by coderanger** [comment]
Hmm, can you tell me which line of your recipe is `classifier-api/recipes/api.rb:70`? That property should only be used at converge time and the default is lazily evaluated. Guessing we might have a naming collision somehow?

**Comment by noradaiko** [comment]
`api.rb` with line numbers:
```
68   gunicorn do
69     port 9001
70     app_module "manage:app"
71   end
```

Because of `no_lazy_load true`?
It is required by Halite.
https://github.com/poise/halite/blob/9fbcca3f4ae89d4efa374a7b9b0c3bace77671ba/lib/halite/converter/libraries.rb#L36

**Comment by coderanger** [comment]
What version of the Poise cookbook and of Chef are you using? It shouldn't be trying to evaluate the default block when you do the set, but it seems confused. Maybe try pulling in Poise from git like you are with the other cookbooks?

**Comment by noradaiko** [comment]
I'm using all poise cookbooks fetched from GitHub:
```
gem 'poise', github: 'poise/poise'
gem 'poise-service', github: 'poise/poise-service'
gem 'poise-application', github: 'poise/application'
gem 'poise-languages', github: 'poise/poise-languages'
gem 'poise-python', github: 'poise/poise-python'
gem 'poise-application-python', github: 'poise/application_python'
gem 'halite'
```

I'm testing with Test-Kitchen and Docker, the chef version is:
```
kitchen@49f351ebd1e1:~$ chef-client --version
Chef: 12.3.0
```

Halite is 1.0.7.
Should I also pull halite from github?

**Comment by coderanger** [comment]
Halite should be fine, let me try my tests on 12.3 though, I only run those integration tests on 12.4 and master right now.

**Comment by noradaiko** [comment]
I tried with chef 12.4.1 and it failed due to same reason on my different server.

**Comment by coderanger** [comment]
I got it to reproduce locally, will tackle fixing it in the morning. Thanks for the report!

**Comment by noradaiko** [comment]
Great, thanks!

**Comment by coderanger** [comment]
So I lied and looked in to it tonight anyway, turns out I just didn't remember how my own code works. Sigh, complicated system is complicated :-(

**Comment by coderanger** [comment]
Lazy defaults aren't as lazy as I thought they were in 12.4. The tests were passing locally because I changed the behavior slightly for 12.5+. Should be fixable, though A bunch of places need the same fix so extra thanks!

**Comment by noradaiko** [comment]
confirmed it's resolved :raised_hands: :star:
