### ISSUE TITLE
unable to deploy python application

### ISSUE THREAD

**Issue by lylianmeyemezu** [poise/application_python#64]
Hi,
I'm trying to install a python application from a private git repo.
According to application_python documentation, this is my recipe 

```
application '/opt/sd-cif' do
  packages   ['git', 'swig', 'openssl-devel']
  owner      'centos'
  group      'centos'
  path       '/opt/sd-cif'
  git '/opt/sd-cif' do
    repository '.......'
    deploy_key 'ssh-rsa ..........'
    revision   'master'
  end  
  python_runtime 'sd-cif' do
  provider :scl
  version '3'
  end
  pip_requirements '/opt/sd-cif/requirements.txt'  
  python_virtualenv '/opt/sd-cif'    
end
```

Error is 
```
[2015-09-30T17:14:02+00:00] DEBUG: Resources for generic application resource enabled on node include: [LWRP resource application from cookbook application]
[2015-09-30T17:14:02+00:00] DEBUG: Resource for application is LWRP resource application from cookbook application
[2015-09-30T17:14:02+00:00] DEBUG: Resources for generic git resource enabled on node include: [Chef::Resource::Git]
[2015-09-30T17:14:02+00:00] DEBUG: Resource for git is Chef::Resource::Git
[2015-09-30T17:14:02+00:00] DEBUG: filtered backtrace of compile error: /var/chef/cache/cookbooks/application_cif/recipes/default.rb:17:in `block (2 levels) in from_file',/var/chef/cache/cookbooks/application_cif/recipes/default.rb:15:in `block in from_file',/var/chef/cache/cookbooks/application_cif/recipes/default.rb:10:in `from_file'
[2015-09-30T17:14:02+00:00] DEBUG: backtrace entry for compile error: '/var/chef/cache/cookbooks/application_cif/recipes/default.rb:17:in `block (2 levels) in from_file''
[2015-09-30T17:14:02+00:00] DEBUG: Line number of compile error: '17'

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/application_cif/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `deploy_key' for Chef::Resource::Git
```

**Comment by coderanger** [comment]
You need the `application_git` cookbook to use the `deploy_key` feature. Add that to your wrapper's metadata.rb dependencies.
