### ISSUE TITLE
Unable to install local wheel package via "python_package" resource

### ISSUE THREAD

**Issue by toddmichael** [poise/application_python#72]
Before requesting admin upload a new Python package to their repo I'm testing via local install.  Installing from command line like so works fine:

```ruby
source /home/fooapp/env/bin/activate && pip install /tmp/kitchen/cache/cefpython3-31.2-cp27-none-linux_x86_64.whl
```

but when I attempt to do via `python_package` resource I have problems.

__Input__

```ruby
# no support for source property so using absolute filename here
python_package /tmp/kitchen/cache/cefpython3-31.2-cp27-none-linux_x86_64.whl do
  virtualenv conf['virtualenv']
end
```

__Output__

```ruby
================================================================================
Error executing action `install` on resource 'python_package[/tmp/kitchen/cache/cefpython3-31.2-cp27-none-linux_x86_64.whl]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of ["/home/fooapp/env/bin/python", "-", "/tmp/kitchen/cache/cefpython3-31.2-cp27-none-linux_x86_64.whl"] ----
STDOUT:
STDERR: /home/fooapp/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
 SNIMissingWarning
/home/fooapp/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
 InsecurePlatformWarning
No handlers could be found for logger "pip.index"
Traceback (most recent call last):
 File "<stdin>", line 38, in <module>
 File "/home/fooapp/env/lib/python2.7/site-packages/pip/index.py", line 491, in find_requirement
'No matching distribution found for %s' % req
```

I use this resource with remote packages all the time with no issues so assume I'm just misusing or otherwise misunderstanding.  Appreciate the assistance.

**Comment by coderanger** [comment]
`python_package` is for installing things from PyPI. There is not currently support for installing local files as there is no good way to do this idempotently without writing my own parser for the filenames and I'm trying hard to avoid that. Use something like this:

```ruby
python_execute "-m pip install #{path}"
```

Idempotence is left as an exercise for the reader :)

**Comment by toddmichael** [comment]
@coderanger, really appreciate the clarification __and__ this excellent cookbook.  just wanted to make sure it wasn't my misunderstanding of proper usage.  i'll use `python_execute`.  cheers.

**Comment by coderanger** [comment]
There are some other tickets up over on `poise-python` about adding some more options to the install process which should make this more directly supportable.
