### ISSUE TITLE
Seems like git is broken

### ISSUE THREAD

**Issue by moos3** [poise/application_python#74]
Thoughts or ideas why I would get this?

```
Generated at 2016-06-30 19:26:02 +0000
Mixlib::ShellOut::ShellCommandFailed: git[https://github.com/moos3/captain-slackhook.git] (wiw_slackhook::default line 7) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git ls-remote "" "HEAD" ----
STDOUT:
STDERR: fatal: No path specified. See 'man git-pull' for valid url syntax
---- End output of git ls-remote "" "HEAD" ----
Ran git ls-remote "" "HEAD" returned 128
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider/git.rb:286:in `git_ls_remote'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider/git.rb:244:in `remote_resolve_reference'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider/git.rb:230:in `target_revision'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider/git.rb:65:in `block (2 levels) in define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:231:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:231:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:321:in `block in run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:320:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/mixin/why_run.rb:320:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:153:in `process_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/provider.rb:132:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:667:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:662:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:662:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:701:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bin/chef-solo:25:in `<top (required)>'
```

**Comment by coderanger** [comment]
What does your recipe code look like?

**Comment by moos3** [comment]
I mean its made simple:
```
include_recipe 'poise-python'

application '/opt/slackhook' do
  git 'https://github.com/moos3/captain-slackhook.git'
  virtualenv
  pip_requirements
  gunicorn do
    port 5050
  end
end
```

berks file which we use metadata.rb:
```
name             'wiw_slackhook'
maintainer       'Richard Genthner'
maintainer_email 'richard.genthner@******************'
license          'All rights reserved'
description      'Installs/Configures a Slack Hook Bot!'
version          IO.read(File.join(File.dirname(__FILE__), 'VERSION')) rescue '0.1.0'

depends 'firewall', '~> 2.4.0'
depends 'build-essential', '~> 2.3.1'
depends 'poise-python'
depends 'application_python', '~> 4.0.0'

#### FOR SMART TESTING
depends 'export-node'

```

**Comment by coderanger** [comment]
Ahh, add `application_git` there too :) You need it for the nicer syntax.

**Comment by coderanger** [comment]
Without application_git you would need this:

```ruby
application '/whatever' do
  git do
    repository 'http://whatever'
  end
  # ...
end
```

**Comment by moos3** [comment]
does gunicorn look for a file name ? because it seems to fail when ?

```
=> default: Recipe: wiw_slackhook::default
==> default:   * application[/opt/slackhook] action restart
==> default:
==> default: * application_gunicorn[/opt/slackhook] action restart
==> default:
==> default: * poise_service[/opt/slackhook] action restart
==> default:
==> default: * service[slackhook] action stop
==> default:  (up to date)
==> default:
==> default: * service[slackhook] action start
==> default:
==> default:
==> default:
==> default: ================================================================================
==> default:
==> default: Error executing action `start` on resource 'service[slackhook]'
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:
==> default:
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:
==> default: ------------------------------------
==> default:
==> default: Expected process to exit with [0], but received '1'
==> default:
==> default:
==> default: ---- Begin output of /sbin/start slackhook ----
==> default:
==> default:
==> default: STDOUT:
==> default:
==> default:
==> default: STDERR: start: Unknown job: slackhook
==> default:
==> default:
==> default: ---- End output of /sbin/start slackhook ----
==> default:
==> default:
==> default: Ran /sbin/start slackhook returned 1
==> default:
==> default:
==> default:
==> default:
==> default: Cookbook Trace:
==> default:
==> default: ---------------
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:74:in `block in action_start'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:134:in `call'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:134:in `notify_if_service'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:73:in `action_start'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/upstart.rb:45:in `action_restart'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:125:in `block in action_restart'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `call'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:154:in `notify_if_service'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:124:in `action_restart'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:249:in `block in proxy_action'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:247:in `proxy_action'
==> default:
==> default:
==> default: /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:229:in `action_restart'
==> default:
==> default:
==> default:
==> default:
==> default: Resource Declaration:
==> default:
==> default: ---------------------
==> default:
==> default: # In /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/wiw_slackhook/recipes/default.rb
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:  11:   gunicorn do
==> default:
==> default:
==> default:  12:     port 5050
==> default:
==> default:
==> default:  13:   end
==> default:
==> default:
==> default:  14: end
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: Compiled Resource:
==> default:
==> default: ------------------
==> default:
==> default: # Declared in /tmp/vagrant-chef/b7e61e11e3322e977613888caee78b78/cookbooks/wiw_slackhook/recipes/default.rb:11:in `block in from_file'
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: service("slackhook") do
==> default:
==> default:
==> default:   provider Chef::Provider::Service::Upstart
==> default:
==> default:
==> default:   action [:nothing]
==> default:
==> default:
==> default:   supports {:status=>true, :restart=>true, :reload=>true}
==> default:
==> default:
==> default:   retries 0
==> default:
==> default:
==> default:   retry_delay 2
==> default:
==> default:
==> default:   default_guard_interpreter :default
==> default:
==> default:
==> default:   service_name "slackhook"
==> default:
==> default:
==> default:   pattern "slackhook"
==> default:
==> default:
==> default: end
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: Platform:
==> default:           ---------
==> default:
==> default:
==> default: x86_64-linux
==> default:
==> default:
==> default:
==> default:
==> default:
```

**Comment by coderanger** [comment]
The Upstart job should be created by the resource. Look above that for a different error.

**Comment by coderanger** [comment]
Closing this out, if you still have issues please let me know.
