### ISSUE TITLE
Chef 14 -  #<NameError: instance variable @cwd not defined>

### ISSUE THREAD

**Issue by Tensibai** [poise/application_python#86]
Issue opened after a talk with coderanger, here's my summary, workaround as comment on the issue:

With the rewrite of the execute resource in Chef 14, the following lines create an error:

```
remove_instance_variable(:@cwd)
```

Error as seen from chefspec test:

```
 expected no Exception, got #<NameError: instance variable @cwd not defined> with backtrace:
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/application_python/files/halite_gem/poise_application_python/resources/python_execute.rb:43:in `remove_instance_variable'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/application_python/files/halite_gem/poise_application_python/resources/python_execute.rb:43:in `initialize'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:140:in `block in declare_resource'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:121:in `declare_resource'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:175:in `public_send'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:175:in `block (2 levels) in _rewire_dsl!'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/app-python/recipes/default.rb:24:in `block in from_file'
         # C:/Users/xxx/AppData/Local/Temp/chefspec20181009-7988-1eo94amfile_cache_path/cookbooks/app-python/recipes/default.rb:21:in `from_file'
         # ./spec/unit/recipes/default_spec.rb:29:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:33:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:33:in `block (3 levels) in <top (required)>'

```

**Comment by Tensibai** [comment]
A workaround given by coderanger:

> coderanger [09:49]
@Tensibai Short term fix would be to copy https://github.com/poise/application_python/blob/master/lib/poise_application_python/resources/python_execute.rb into a library file, change the `provides`, and change all the `remove_instance_variable` calls to end with `rescue nil`, inelegant but would work on both 13 and 14.

>The slightly hulksmash approach would be something like `remove_instance_variable(:@foo) if defined?(@foo)` for each of them

What I ended doing is mostly that, copying the file into my cookbook libraries directory and editing the 3 lines as follow:

```
          remove_instance_variable(:@cwd) if defined?(@cwd)
          remove_instance_variable(:@group) if defined?(@group)
          remove_instance_variable(:@user) if defined?(@user)
```
